FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir elasticsearch

COPY services/search/ .

CMD ["python", "services/search/main.py"]
